"""add user_id to ingredients recipes meal_plans

Revision ID: c73649e6b851
Revises: 04c29726cc00
Create Date: 2026-07-18 20:16:06.849044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c73649e6b851'
down_revision: Union[str, Sequence[str], None] = '04c29726cc00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ingredients', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('meal_plans', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'meal_plans', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('recipes', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'recipes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'user_id')
    op.drop_constraint(None, 'meal_plans', type_='foreignkey')
    op.drop_column('meal_plans', 'user_id')
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.drop_column('ingredients', 'user_id')
    # ### end Alembic commands ###
